#!/usr/bin/env python3
"""Audit public GitHub surfaces outside default-branch file trees.

Copyright © 2026 Gateway Information Group LLC. All rights reserved.
"""
from __future__ import annotations

import json
import os
import re
import time
import urllib.error
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = ROOT / ".github" / "portfolio-manifest.json"
OUTPUT_DIR = ROOT / "audit-output"
RIGHTS_NOTICE = "Copyright © 2026 Gateway Information Group LLC. All rights reserved."
USER_AGENT = "Gateway-Public-GitHub-Surface-Audit/1.0"
HTTP_TIMEOUT_SECONDS = 20
HTTP_ATTEMPTS = 3
MAX_RECORDS_PER_ENDPOINT = 100
MAX_TEXT_BYTES = 1_000_000
MAX_FINDINGS = 300

PRIVATE_KEY_PATTERN = re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----")
SECRET_PATTERNS = [
    ("secret.github_token", re.compile(r"\b(?:gh[pousr]_[A-Za-z0-9_]{30,}|github_pat_[A-Za-z0-9_]{30,})\b")),
    ("secret.aws_access_key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("secret.openai_key", re.compile(r"\bsk-(?:proj-)?[A-Za-z0-9_-]{24,}\b")),
    ("secret.slack_token", re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{20,}\b")),
    ("secret.google_api_key", re.compile(r"\bAIza[0-9A-Za-z_-]{30,}\b")),
]
GENERIC_SECRET_ASSIGNMENT = re.compile(
    r"(?i)\b(?:api[_-]?key|access[_-]?token|auth[_-]?token|client[_-]?secret|password|"
    r"private[_-]?key|secret)\b\s*[:=]\s*[\"']([^\"'\r\n]{12,})[\"']"
)
PLACEHOLDER_WORDS = {
    "changeme",
    "dummy",
    "example",
    "placeholder",
    "redacted",
    "replace",
    "sample",
    "test",
    "your_",
    "your-",
}
WINDOWS_USER_PATH = re.compile(r"(?i)\b[A-Z]:\\Users\\([^\\\r\n]+)\\")
UNIX_USER_PATH = re.compile(r"/(?:home|Users)/([A-Za-z0-9._-]+)/")
GENERIC_USER_NAMES = {"example", "github", "runner", "user", "username"}
EMAIL_PATTERN = re.compile(r"(?<![\w.+-])([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})(?![\w.-])")
PHONE_PATTERN = re.compile(r"(?<!\d)(?:\+1[-.\s]?)?(?:\(\d{3}\)|\d{3})[-.\s]\d{3}[-.\s]\d{4}(?!\d)")
ALLOWED_EMAIL_DOMAINS = {
    "example.com",
    "example.invalid",
    "example.org",
    "users.noreply.github.com",
}
INTERNAL_LINK_PATTERN = re.compile(
    r"(?i)https?://(?:chatgpt\.com/(?:g/|c/|share/)|"
    r"docs\.google\.com/(?:document|spreadsheets|presentation)/d/|"
    r"drive\.google\.com/(?:file/d/|drive/folders/))"
)
PUBLIC_COPY_PATTERNS = [
    ("copy.value_add", re.compile(r"(?i)\bvalue[- ]add\b")),
    ("copy.prompt_process", re.compile(r"(?i)\b(?:prompt strategy|prompt engineering|system prompt|developer prompt|prompt chain)\b")),
    ("copy.ai_process", re.compile(r"(?i)\b(?:chatgpt|codex|openai|large language model|ai-generated|generated by ai|written by ai)\b")),
    ("copy.backend_speak", re.compile(r"(?i)\b(?:backend speak|behind[- ]the[- ]scenes process)\b")),
    ("copy.audience_meta", re.compile(r"(?i)\b(?:recruiter-facing|recruiter-visible|portfolio-facing|reviewer-facing|public-facing copy)\b")),
    ("copy.publication_meta", re.compile(r"(?i)\b(?:publication gate|publication process|operating proof|proof point|portfolio evidence)\b")),
]
SENSITIVE_ASSET_SUFFIXES = {".key", ".kdbx", ".keystore", ".p12", ".pem", ".pfx", ".jks", ".env"}
INTERNAL_ASSET_PATTERN = re.compile(
    r"(?i)(?:chatgpt|codex|prompt|handoff|support[_ -]?export|upload[_ -]?this|"
    r"thread[_ -]?parameters|conversation|private[_ -]?notes|internal[_ -]?notes)"
)


@dataclass(frozen=True)
class Finding:
    severity: str
    rule: str
    repository: str
    surface: str
    message: str
    excerpt: str


@dataclass
class RepositoryResult:
    repository: str
    open_issues_scanned: int = 0
    open_prs_scanned: int = 0
    releases_scanned: int = 0
    release_assets_inspected: int = 0
    findings: list[Finding] = field(default_factory=list)


def headers() -> dict[str, str]:
    result = {
        "Accept": "application/vnd.github+json",
        "User-Agent": USER_AGENT,
        "X-GitHub-Api-Version": "2022-11-28",
    }
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    if token:
        result["Authorization"] = f"Bearer {token}"
    return result


def request_json(url: str) -> Any:
    last_error: Exception | None = None
    for attempt in range(1, HTTP_ATTEMPTS + 1):
        try:
            request = urllib.request.Request(url, headers=headers())
            with urllib.request.urlopen(request, timeout=HTTP_TIMEOUT_SECONDS) as response:
                data = response.read(MAX_TEXT_BYTES + 1)
                if len(data) > MAX_TEXT_BYTES:
                    raise ValueError(f"response exceeds {MAX_TEXT_BYTES} bytes")
                return json.loads(data.decode("utf-8"))
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError, ValueError, json.JSONDecodeError) as exc:
            last_error = exc
            if attempt < HTTP_ATTEMPTS:
                time.sleep(0.75 * attempt)
    raise RuntimeError(f"{url}: {last_error}")


def load_manifest() -> dict[str, Any]:
    payload = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    if payload.get("schema_version") != 1:
        raise SystemExit("Unsupported portfolio manifest schema")
    return payload


def safe_excerpt(value: str, *, sensitive: bool) -> str:
    if sensitive:
        return "[candidate value redacted]"
    compact = re.sub(r"\s+", " ", value.strip())
    for _, pattern in SECRET_PATTERNS:
        compact = pattern.sub("[REDACTED]", compact)
    compact = EMAIL_PATTERN.sub("[EMAIL]", compact)
    compact = PHONE_PATTERN.sub("[PHONE]", compact)
    return compact[:180]


def add_finding(
    result: RepositoryResult,
    *,
    severity: str,
    rule: str,
    surface: str,
    message: str,
    excerpt: str = "",
    sensitive: bool = False,
) -> None:
    if len(result.findings) >= MAX_FINDINGS:
        return
    result.findings.append(
        Finding(
            severity=severity,
            rule=rule,
            repository=result.repository,
            surface=surface,
            message=message,
            excerpt=safe_excerpt(excerpt, sensitive=sensitive),
        )
    )


def scan_text(
    result: RepositoryResult,
    *,
    surface: str,
    text: str,
    apply_public_copy: bool,
) -> None:
    if PRIVATE_KEY_PATTERN.search(text):
        add_finding(
            result,
            severity="error",
            rule="secret.private_key_block",
            surface=surface,
            message="Private-key material marker is present.",
            sensitive=True,
        )
    for rule, pattern in SECRET_PATTERNS:
        if pattern.search(text):
            add_finding(
                result,
                severity="error",
                rule=rule,
                surface=surface,
                message="Credential-shaped value is present.",
                sensitive=True,
            )
    for match in GENERIC_SECRET_ASSIGNMENT.finditer(text):
        candidate = match.group(1).strip().lower()
        if any(word in candidate for word in PLACEHOLDER_WORDS):
            continue
        add_finding(
            result,
            severity="error",
            rule="secret.assigned_value",
            surface=surface,
            message="A credential-like field contains a non-placeholder assigned value.",
            sensitive=True,
        )
    for line in text.splitlines():
        for match in WINDOWS_USER_PATH.finditer(line):
            username = match.group(1).strip().lower()
            if username not in GENERIC_USER_NAMES:
                add_finding(
                    result,
                    severity="warning",
                    rule="privacy.absolute_user_path",
                    surface=surface,
                    message="A Windows user-profile path may expose machine-local identity or layout.",
                    excerpt=line,
                    sensitive=True,
                )
        for match in UNIX_USER_PATH.finditer(line):
            username = match.group(1).strip().lower()
            if username not in GENERIC_USER_NAMES:
                add_finding(
                    result,
                    severity="warning",
                    rule="privacy.absolute_user_path",
                    surface=surface,
                    message="A Unix or macOS user-home path may expose machine-local identity or layout.",
                    excerpt=line,
                    sensitive=True,
                )
        for match in EMAIL_PATTERN.finditer(line):
            domain = match.group(1).rsplit("@", 1)[-1].lower()
            if domain not in ALLOWED_EMAIL_DOMAINS:
                add_finding(
                    result,
                    severity="warning",
                    rule="privacy.email_address",
                    surface=surface,
                    message="Email address requires confirmation that publication is intentional.",
                    excerpt=line,
                    sensitive=True,
                )
        if PHONE_PATTERN.search(line):
            add_finding(
                result,
                severity="warning",
                rule="privacy.phone_number",
                surface=surface,
                message="Phone-number-shaped text requires confirmation that publication is intentional.",
                excerpt=line,
                sensitive=True,
            )
        if INTERNAL_LINK_PATTERN.search(line):
            add_finding(
                result,
                severity="warning",
                rule="privacy.collaboration_link",
                surface=surface,
                message="A collaboration or conversation link requires confirmation that public access is intentional.",
                excerpt=line,
                sensitive=True,
            )
        if apply_public_copy:
            for rule, pattern in PUBLIC_COPY_PATTERNS:
                if pattern.search(line):
                    add_finding(
                        result,
                        severity="warning",
                        rule=rule,
                        surface=surface,
                        message="Release copy uses internal process or audience-meta language instead of showing the result directly.",
                        excerpt=line,
                    )


def scan_release_asset(result: RepositoryResult, release_surface: str, asset: dict[str, Any]) -> None:
    name = str(asset.get("name") or "").strip()
    result.release_assets_inspected += 1
    lower_name = name.lower()
    suffix = "." + lower_name.rsplit(".", 1)[-1] if "." in lower_name else ""
    if suffix in SENSITIVE_ASSET_SUFFIXES or lower_name == ".env":
        add_finding(
            result,
            severity="error",
            rule="release.sensitive_asset_type",
            surface=f"{release_surface}/asset/{name}",
            message="Release asset has a credential or private-key file type.",
        )
    if INTERNAL_ASSET_PATTERN.search(name):
        add_finding(
            result,
            severity="warning",
            rule="release.internal_asset_name",
            surface=f"{release_surface}/asset/{name}",
            message="Release asset name suggests an internal handoff, prompt, conversation, or support package.",
            excerpt=name,
        )
    if WINDOWS_USER_PATH.search(name) or UNIX_USER_PATH.search(name):
        add_finding(
            result,
            severity="warning",
            rule="privacy.absolute_user_path",
            surface=f"{release_surface}/asset/{name}",
            message="Release asset name contains a user-home path.",
            sensitive=True,
        )


def audit_repository(owner: str, repository: str) -> RepositoryResult:
    result = RepositoryResult(repository=repository)
    quoted_owner = urllib.parse.quote(owner, safe="")
    quoted_repo = urllib.parse.quote(repository, safe="")
    try:
        issues = request_json(
            f"https://api.github.com/repos/{quoted_owner}/{quoted_repo}/issues"
            f"?state=open&per_page={MAX_RECORDS_PER_ENDPOINT}"
        )
        if not isinstance(issues, list):
            raise ValueError("open issue response is not a list")
        if len(issues) == MAX_RECORDS_PER_ENDPOINT:
            add_finding(
                result,
                severity="warning",
                rule="coverage.open_records_limit",
                surface="issues",
                message="Open issue/PR scan reached the configured first-page limit.",
            )
        for item in issues:
            number = int(item.get("number") or 0)
            is_pr = "pull_request" in item
            surface = f"{'pulls' if is_pr else 'issues'}/{number}"
            if is_pr:
                result.open_prs_scanned += 1
            else:
                result.open_issues_scanned += 1
            text = f"{item.get('title') or ''}\n{item.get('body') or ''}"
            scan_text(result, surface=surface, text=text, apply_public_copy=False)

        releases = request_json(
            f"https://api.github.com/repos/{quoted_owner}/{quoted_repo}/releases"
            f"?per_page={MAX_RECORDS_PER_ENDPOINT}"
        )
        if not isinstance(releases, list):
            raise ValueError("release response is not a list")
        public_releases = [item for item in releases if not item.get("draft", False)]
        if len(releases) == MAX_RECORDS_PER_ENDPOINT:
            add_finding(
                result,
                severity="warning",
                rule="coverage.release_limit",
                surface="releases",
                message="Release scan reached the configured first-page limit.",
            )
        for item in public_releases:
            release_id = int(item.get("id") or 0)
            tag = str(item.get("tag_name") or "untagged")
            surface = f"releases/{release_id}:{tag}"
            result.releases_scanned += 1
            text = "\n".join(
                [
                    str(item.get("name") or ""),
                    tag,
                    str(item.get("body") or ""),
                ]
            )
            scan_text(result, surface=surface, text=text, apply_public_copy=True)
            for asset in item.get("assets") or []:
                if isinstance(asset, dict):
                    scan_release_asset(result, surface, asset)
    except Exception as exc:
        add_finding(
            result,
            severity="error",
            rule="coverage.surface_unreadable",
            surface="repository",
            message=f"Public GitHub surfaces could not be scanned completely: {type(exc).__name__}: {exc}",
        )
    return result


def write_reports(manifest: dict[str, Any], results: list[RepositoryResult]) -> tuple[int, int]:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    findings = [finding for result in results for finding in result.findings]
    findings.sort(
        key=lambda item: (
            item.severity != "error",
            item.repository.lower(),
            item.surface,
            item.rule,
        )
    )
    errors = [item for item in findings if item.severity == "error"]
    warnings = [item for item in findings if item.severity == "warning"]
    generated_utc = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    payload = {
        "schema_version": 1,
        "generated_utc": generated_utc,
        "owner": manifest["owner"],
        "rights_notice": RIGHTS_NOTICE,
        "repositories_expected": len(manifest["expected_public_repositories"]),
        "repositories_scanned": len(results),
        "open_issues_scanned": sum(item.open_issues_scanned for item in results),
        "open_prs_scanned": sum(item.open_prs_scanned for item in results),
        "releases_scanned": sum(item.releases_scanned for item in results),
        "release_assets_inspected": sum(item.release_assets_inspected for item in results),
        "error_count": len(errors),
        "warning_count": len(warnings),
        "repositories": [
            {
                "repository": item.repository,
                "open_issues_scanned": item.open_issues_scanned,
                "open_prs_scanned": item.open_prs_scanned,
                "releases_scanned": item.releases_scanned,
                "release_assets_inspected": item.release_assets_inspected,
                "error_count": sum(1 for finding in item.findings if finding.severity == "error"),
                "warning_count": sum(1 for finding in item.findings if finding.severity == "warning"),
            }
            for item in results
        ],
        "findings": [asdict(item) for item in findings],
    }
    (OUTPUT_DIR / "public-github-surfaces.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    lines = [
        "# Public GitHub surface audit",
        "",
        f"Generated: `{generated_utc}`",
        "",
        f"- Repositories: **{len(results)}/{len(manifest['expected_public_repositories'])}**",
        f"- Open issues scanned: **{payload['open_issues_scanned']}**",
        f"- Open pull requests scanned: **{payload['open_prs_scanned']}**",
        f"- Releases scanned: **{payload['releases_scanned']}**",
        f"- Release assets inspected: **{payload['release_assets_inspected']}**",
        f"- Errors: **{len(errors)}**",
        f"- Warnings: **{len(warnings)}**",
        "",
        "## Repository coverage",
        "",
        "| Repository | Issues | PRs | Releases | Assets | Errors | Warnings |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for item in results:
        lines.append(
            f"| {item.repository} | {item.open_issues_scanned} | {item.open_prs_scanned} | "
            f"{item.releases_scanned} | {item.release_assets_inspected} | "
            f"{sum(1 for finding in item.findings if finding.severity == 'error')} | "
            f"{sum(1 for finding in item.findings if finding.severity == 'warning')} |"
        )
    lines.extend(["", "## Findings", ""])
    if not findings:
        lines.append("No findings.")
    else:
        for item in findings:
            lines.append(
                f"- **{item.severity.upper()}** `{item.repository}/{item.surface}` "
                f"`{item.rule}` — {item.message}"
            )
            if item.excerpt:
                lines.append(f"  - `{item.excerpt}`")
    lines.extend(
        [
            "",
            RIGHTS_NOTICE,
            "",
            "This notice does not replace or infer a software license. Third-party components retain their respective notices and licenses.",
            "",
        ]
    )
    (OUTPUT_DIR / "public-github-surfaces.md").write_text("\n".join(lines), encoding="utf-8")
    return len(errors), len(warnings)


def main() -> int:
    manifest = load_manifest()
    owner = str(manifest["owner"])
    repositories = list(manifest["expected_public_repositories"])
    results: list[RepositoryResult] = []
    with ThreadPoolExecutor(max_workers=4) as executor:
        futures = {
            executor.submit(audit_repository, owner, str(repository)): str(repository)
            for repository in repositories
        }
        for future in as_completed(futures):
            repository = futures[future]
            try:
                results.append(future.result())
            except Exception as exc:
                result = RepositoryResult(repository=repository)
                add_finding(
                    result,
                    severity="error",
                    rule="coverage.unexpected_failure",
                    surface="repository",
                    message=f"Unexpected surface-audit failure: {type(exc).__name__}: {exc}",
                )
                results.append(result)
    results.sort(key=lambda item: item.repository.lower())
    errors, warnings = write_reports(manifest, results)
    print(
        "Public GitHub surface audit: "
        f"repositories={len(results)} errors={errors} warnings={warnings}"
    )
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
