#!/usr/bin/env python3
"""Read-only sanitation and public-copy audit for every declared public repository.

Copyright © 2026 Gateway Information Group LLC. All rights reserved.
"""
from __future__ import annotations

import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = ROOT / ".github" / "portfolio-manifest.json"
OUTPUT_DIR = Path(os.environ.get("PORTFOLIO_AUDIT_OUTPUT_DIR", ROOT / "audit-output"))
RIGHTS_NOTICE = "Copyright © 2026 Gateway Information Group LLC. All rights reserved."
USER_AGENT = "Gateway-Public-Sanitization-Audit/1.0"
HTTP_TIMEOUT_SECONDS = 20
HTTP_ATTEMPTS = 3
MAX_FILE_BYTES = 2_000_000
MAX_FILES_PER_REPOSITORY = 1_500
MAX_BYTES_PER_REPOSITORY = 30_000_000
MAX_FINDINGS = 500

TEXT_SUFFIXES = {
    ".bat",
    ".cfg",
    ".cmd",
    ".conf",
    ".css",
    ".csv",
    ".editorconfig",
    ".example",
    ".gitattributes",
    ".gitignore",
    ".htm",
    ".html",
    ".ini",
    ".ipynb",
    ".js",
    ".json",
    ".jsx",
    ".md",
    ".mjs",
    ".ps1",
    ".psd1",
    ".psm1",
    ".py",
    ".rst",
    ".sh",
    ".toml",
    ".ts",
    ".tsx",
    ".txt",
    ".xml",
    ".yaml",
    ".yml",
}
TEXT_FILENAMES = {
    "dockerfile",
    "license",
    "makefile",
    "notice",
    "procfile",
    "security",
}
SECRET_FILE_SUFFIXES = {".key", ".kdbx", ".keystore", ".p12", ".pem", ".pfx", ".jks"}
RUNTIME_OR_ARCHIVE_SUFFIXES = {
    ".7z",
    ".bak",
    ".db",
    ".dmp",
    ".gz",
    ".log",
    ".rar",
    ".sqlite",
    ".sqlite3",
    ".tar",
    ".tmp",
    ".zip",
}
SKIP_PATH_PARTS = {".git", ".venv", "audit-output", "node_modules", "__pycache__"}

INTERNAL_PATH_PATTERN = re.compile(
    r"(?i)(?:^|/)(?:chatgpt|codex|openai|prompt(?:s)?|handoff|transfer(?:[_ -]summary)?|"
    r"support[_ -]?export|upload[_ -]?this|thread[_ -]?parameters|conversation|scratch|"
    r"private[_ -]?notes|internal[_ -]?notes)(?:[./ _-]|$)"
)
RUNTIME_PATH_PATTERN = re.compile(r"(?i)(?:^|/)(?:diagnostics?|exports?|logs?|state|temp|tmp)(?:/|$)")

PRIVATE_KEY_PATTERN = re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----")
SECRET_PATTERNS = [
    ("secret.github_token", re.compile(r"\b(?:gh[pousr]_[A-Za-z0-9_]{30,}|github_pat_[A-Za-z0-9_]{30,})\b")),
    ("secret.aws_access_key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("secret.openai_key", re.compile(r"\bsk-(?:proj-)?[A-Za-z0-9_-]{24,}\b")),
    ("secret.slack_token", re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{20,}\b")),
    ("secret.google_api_key", re.compile(r"\bAIza[0-9A-Za-z_-]{30,}\b")),
]
GENERIC_SECRET_ASSIGNMENT = re.compile(
    r"(?i)\b(?:api[_-]?key|access[_-]?token|auth[_-]?token|client[_-]?secret|password|"
    r"private[_-]?key|secret)\b\s*[:=]\s*[\"']([^\"'\r\n]{12,})[\"']"
)
PLACEHOLDER_WORDS = {
    "changeme",
    "dummy",
    "example",
    "placeholder",
    "redacted",
    "replace",
    "sample",
    "test",
    "your_",
    "your-",
}

WINDOWS_USER_PATH = re.compile(r"(?i)\b[A-Z]:\\Users\\([^\\\r\n]+)\\")
UNIX_USER_PATH = re.compile(r"/(?:home|Users)/([^/\s]+)/")
EMAIL_PATTERN = re.compile(r"(?<![\w.+-])([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})(?![\w.-])")
PHONE_PATTERN = re.compile(r"(?<!\d)(?:\+1[-.\s]?)?(?:\(\d{3}\)|\d{3})[-.\s]\d{3}[-.\s]\d{4}(?!\d)")
ALLOWED_EMAIL_DOMAINS = {"example.com", "example.org", "users.noreply.github.com"}
GENERIC_USER_NAMES = {"example", "github", "runner", "user", "username"}

PUBLIC_COPY_PATTERNS = [
    ("copy.value_add", re.compile(r"(?i)\bvalue[- ]add\b")),
    ("copy.prompt_process", re.compile(r"(?i)\b(?:prompt strategy|prompt engineering|system prompt|developer prompt|prompt chain)\b")),
    ("copy.ai_process", re.compile(r"(?i)\b(?:chatgpt|codex|openai|large language model|ai-generated|generated by ai|written by ai)\b")),
    ("copy.backend_speak", re.compile(r"(?i)\b(?:backend speak|behind[- ]the[- ]scenes process)\b")),
    ("copy.audience_meta", re.compile(r"(?i)\b(?:recruiter-facing|recruiter-visible|portfolio-facing|reviewer-facing|public-facing copy)\b")),
    ("copy.publication_meta", re.compile(r"(?i)\b(?:publication gate|publication process|operating proof|proof point|portfolio evidence)\b")),
]

TECHNICAL_MARKDOWN_NAMES = {
    "architecture.md",
    "changelog.md",
    "contributing.md",
    "decisions.md",
    "license.md",
    "privacy.md",
    "release_reconciliation.md",
    "risk_disclosure.md",
    "security.md",
    "security_audit.md",
    "testing.md",
    "third_party_notices.md",
    "threat_model.md",
}


@dataclass(frozen=True)
class Finding:
    severity: str
    rule: str
    repository: str
    path: str
    line: int | None
    message: str
    excerpt: str


@dataclass
class RepositoryResult:
    repository: str
    files_seen: int = 0
    text_files_scanned: int = 0
    bytes_scanned: int = 0
    skipped_large_files: int = 0
    findings: list[Finding] | None = None

    def __post_init__(self) -> None:
        if self.findings is None:
            self.findings = []


def _headers(url: str) -> dict[str, str]:
    headers = {"User-Agent": USER_AGENT}
    if (urllib.parse.urlparse(url).hostname or "").lower() == "api.github.com":
        headers["Accept"] = "application/vnd.github+json"
        headers["X-GitHub-Api-Version"] = "2022-11-28"
        token = os.environ.get("GITHUB_TOKEN", "").strip()
        if token:
            headers["Authorization"] = f"Bearer {token}"
    return headers


def request_bytes(url: str, *, max_bytes: int) -> bytes:
    last_error: Exception | None = None
    for attempt in range(1, HTTP_ATTEMPTS + 1):
        try:
            request = urllib.request.Request(url, headers=_headers(url))
            with urllib.request.urlopen(request, timeout=HTTP_TIMEOUT_SECONDS) as response:
                data = response.read(max_bytes + 1)
                if len(data) > max_bytes:
                    raise ValueError(f"response exceeds {max_bytes} bytes")
                return data
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError, ValueError) as exc:
            last_error = exc
            if attempt < HTTP_ATTEMPTS:
                time.sleep(0.75 * attempt)
    raise RuntimeError(f"{url}: {last_error}")


def request_json(url: str) -> Any:
    return json.loads(request_bytes(url, max_bytes=8_000_000).decode("utf-8"))


def load_manifest() -> dict[str, Any]:
    data = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1:
        raise SystemExit("Unsupported portfolio manifest schema")
    return data


def raw_url(owner: str, repository: str, branch: str, path: str) -> str:
    quoted_path = "/".join(urllib.parse.quote(part, safe="") for part in path.split("/"))
    return (
        "https://raw.githubusercontent.com/"
        f"{urllib.parse.quote(owner, safe='')}/"
        f"{urllib.parse.quote(repository, safe='')}/"
        f"{urllib.parse.quote(branch, safe='')}/{quoted_path}"
    )


def is_text_path(path: str) -> bool:
    item = PurePosixPath(path)
    return item.suffix.lower() in TEXT_SUFFIXES or item.name.lower() in TEXT_FILENAMES


def is_public_copy_path(path: str) -> bool:
    item = PurePosixPath(path)
    lower_path = path.lower()
    name = item.name.lower()
    if name == "readme.md" or name in {"faq.md", "quickstart.md", "start_here.md"}:
        return True
    if item.suffix.lower() in {".html", ".htm"}:
        return True
    if lower_path.startswith("docs/") and item.suffix.lower() in {".md", ".rst"}:
        return name not in TECHNICAL_MARKDOWN_NAMES
    return False


def sanitized_excerpt(line: str, *, sensitive: bool) -> str:
    if sensitive:
        return "[candidate value redacted]"
    compact = re.sub(r"\s+", " ", line.strip())
    for _, pattern in SECRET_PATTERNS:
        compact = pattern.sub("[REDACTED]", compact)
    compact = EMAIL_PATTERN.sub("[EMAIL]", compact)
    compact = PHONE_PATTERN.sub("[PHONE]", compact)
    return compact[:180]


def add_finding(
    result: RepositoryResult,
    *,
    severity: str,
    rule: str,
    path: str,
    line: int | None,
    message: str,
    excerpt: str = "",
    sensitive: bool = False,
) -> None:
    if len(result.findings or []) >= MAX_FINDINGS:
        return
    assert result.findings is not None
    result.findings.append(
        Finding(
            severity=severity,
            rule=rule,
            repository=result.repository,
            path=path,
            line=line,
            message=message,
            excerpt=sanitized_excerpt(excerpt, sensitive=sensitive),
        )
    )


def scan_path(result: RepositoryResult, path: str, size: int | None) -> None:
    item = PurePosixPath(path)
    suffix = item.suffix.lower()
    lower_path = path.lower()

    if path == ".env" or suffix in SECRET_FILE_SUFFIXES:
        add_finding(
            result,
            severity="error",
            rule="path.secret_material",
            path=path,
            line=None,
            message="Credential or private-key file type is tracked publicly.",
        )
    elif suffix in RUNTIME_OR_ARCHIVE_SUFFIXES:
        add_finding(
            result,
            severity="warning",
            rule="path.runtime_or_archive",
            path=path,
            line=None,
            message="Archive, runtime-state, database, log, dump, or backup file needs public-release review.",
        )

    if INTERNAL_PATH_PATTERN.search(path):
        add_finding(
            result,
            severity="warning",
            rule="path.internal_process_artifact",
            path=path,
            line=None,
            message="Filename suggests internal drafting, transfer, prompt, or support-handoff material.",
        )
    if RUNTIME_PATH_PATTERN.search(path):
        add_finding(
            result,
            severity="warning",
            rule="path.runtime_directory",
            path=path,
            line=None,
            message="Tracked file appears inside a runtime output directory.",
        )
    if size is not None and size > MAX_FILE_BYTES and is_text_path(path):
        result.skipped_large_files += 1
        add_finding(
            result,
            severity="warning",
            rule="coverage.large_text_file",
            path=path,
            line=None,
            message=f"Text-like file exceeds the {MAX_FILE_BYTES}-byte scan limit.",
        )
    if lower_path.endswith(".env.example"):
        return


def scan_text(result: RepositoryResult, path: str, data: bytes) -> None:
    if b"\x00" in data[:4096]:
        return
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        text = data.decode("utf-8", errors="replace")
    result.text_files_scanned += 1
    result.bytes_scanned += len(data)
    lines = text.splitlines()

    if PRIVATE_KEY_PATTERN.search(text):
        line_number = text[: PRIVATE_KEY_PATTERN.search(text).start()].count("\n") + 1  # type: ignore[union-attr]
        add_finding(
            result,
            severity="error",
            rule="secret.private_key_block",
            path=path,
            line=line_number,
            message="Private-key material marker is present.",
            sensitive=True,
        )

    for rule, pattern in SECRET_PATTERNS:
        for match in pattern.finditer(text):
            line_number = text[: match.start()].count("\n") + 1
            add_finding(
                result,
                severity="error",
                rule=rule,
                path=path,
                line=line_number,
                message="Credential-shaped value is present.",
                sensitive=True,
            )

    for match in GENERIC_SECRET_ASSIGNMENT.finditer(text):
        candidate = match.group(1).strip()
        lower_candidate = candidate.lower()
        if any(word in lower_candidate for word in PLACEHOLDER_WORDS):
            continue
        line_number = text[: match.start()].count("\n") + 1
        add_finding(
            result,
            severity="error",
            rule="secret.assigned_value",
            path=path,
            line=line_number,
            message="A credential-like field contains a non-placeholder assigned value.",
            sensitive=True,
        )

    for line_number, line in enumerate(lines, start=1):
        for match in WINDOWS_USER_PATH.finditer(line):
            username = match.group(1).strip().lower()
            if username not in GENERIC_USER_NAMES:
                add_finding(
                    result,
                    severity="warning",
                    rule="privacy.absolute_user_path",
                    path=path,
                    line=line_number,
                    message="A Windows user-profile path may reveal machine-local identity or layout.",
                    excerpt=line,
                    sensitive=True,
                )
        for match in UNIX_USER_PATH.finditer(line):
            username = match.group(1).strip().lower()
            if username not in GENERIC_USER_NAMES:
                add_finding(
                    result,
                    severity="warning",
                    rule="privacy.absolute_user_path",
                    path=path,
                    line=line_number,
                    message="A Unix or macOS user-home path may reveal machine-local identity or layout.",
                    excerpt=line,
                    sensitive=True,
                )
        for email_match in EMAIL_PATTERN.finditer(line):
            address = email_match.group(1)
            domain = address.rsplit("@", 1)[-1].lower()
            if domain not in ALLOWED_EMAIL_DOMAINS:
                add_finding(
                    result,
                    severity="warning",
                    rule="privacy.email_address",
                    path=path,
                    line=line_number,
                    message="Email address requires confirmation that publication is intentional.",
                    excerpt=line,
                    sensitive=True,
                )
        if PHONE_PATTERN.search(line):
            add_finding(
                result,
                severity="warning",
                rule="privacy.phone_number",
                path=path,
                line=line_number,
                message="Phone-number-shaped text requires confirmation that publication is intentional.",
                excerpt=line,
                sensitive=True,
            )

        if is_public_copy_path(path):
            for rule, pattern in PUBLIC_COPY_PATTERNS:
                if pattern.search(line):
                    add_finding(
                        result,
                        severity="warning",
                        rule=rule,
                        path=path,
                        line=line_number,
                        message="Public copy uses process-oriented or audience-meta language instead of showing the result directly.",
                        excerpt=line,
                    )


def local_repository_files() -> list[tuple[str, int, bytes | None]]:
    records: list[tuple[str, int, bytes | None]] = []
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(ROOT)
        if any(part in SKIP_PATH_PARTS for part in rel.parts):
            continue
        rel_text = rel.as_posix()
        size = path.stat().st_size
        data = None
        if is_text_path(rel_text) and size <= MAX_FILE_BYTES:
            data = path.read_bytes()
        records.append((rel_text, size, data))
    return records


def remote_repository_files(owner: str, repository: str) -> list[tuple[str, int, bytes | None]]:
    metadata = request_json(
        f"https://api.github.com/repos/{urllib.parse.quote(owner, safe='')}/"
        f"{urllib.parse.quote(repository, safe='')}"
    )
    branch = metadata.get("default_branch") or "main"
    tree = request_json(
        f"https://api.github.com/repos/{urllib.parse.quote(owner, safe='')}/"
        f"{urllib.parse.quote(repository, safe='')}/git/trees/"
        f"{urllib.parse.quote(branch, safe='')}?recursive=1"
    )
    if tree.get("truncated"):
        raise RuntimeError("recursive tree response was truncated")
    entries = [item for item in tree.get("tree", []) if item.get("type") == "blob"]
    if len(entries) > MAX_FILES_PER_REPOSITORY:
        raise RuntimeError(f"repository has {len(entries)} files; limit is {MAX_FILES_PER_REPOSITORY}")

    records: list[tuple[str, int, bytes | None]] = []
    total_declared_bytes = 0
    for item in sorted(entries, key=lambda value: str(value.get("path", ""))):
        path = str(item.get("path", ""))
        size = int(item.get("size") or 0)
        total_declared_bytes += size
        if total_declared_bytes > MAX_BYTES_PER_REPOSITORY:
            raise RuntimeError(
                f"declared repository bytes exceed the {MAX_BYTES_PER_REPOSITORY}-byte scan bound"
            )
        data = None
        if is_text_path(path) and size <= MAX_FILE_BYTES:
            data = request_bytes(raw_url(owner, repository, branch, path), max_bytes=MAX_FILE_BYTES)
        records.append((path, size, data))
    return records


def scan_repository(owner: str, repository: str, profile_repository: str) -> RepositoryResult:
    result = RepositoryResult(repository=repository)
    try:
        records = (
            local_repository_files()
            if repository == profile_repository
            else remote_repository_files(owner, repository)
        )
        for path, size, data in records:
            result.files_seen += 1
            scan_path(result, path, size)
            if data is not None:
                scan_text(result, path, data)
    except Exception as exc:
        add_finding(
            result,
            severity="error",
            rule="coverage.repository_unreadable",
            path="",
            line=None,
            message=f"Repository could not be scanned completely: {type(exc).__name__}: {exc}",
        )
    return result


def write_reports(manifest: dict[str, Any], results: list[RepositoryResult]) -> tuple[int, int]:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    findings = [finding for result in results for finding in (result.findings or [])]
    findings.sort(key=lambda item: (item.severity != "error", item.repository, item.path, item.line or 0, item.rule))
    errors = [item for item in findings if item.severity == "error"]
    warnings = [item for item in findings if item.severity == "warning"]
    generated_utc = datetime.now(timezone.utc).replace(microsecond=0).isoformat()

    payload = {
        "schema_version": 1,
        "generated_utc": generated_utc,
        "owner": manifest["owner"],
        "rights_notice": RIGHTS_NOTICE,
        "repositories_expected": len(manifest["expected_public_repositories"]),
        "repositories_scanned": len(results),
        "files_seen": sum(item.files_seen for item in results),
        "text_files_scanned": sum(item.text_files_scanned for item in results),
        "bytes_scanned": sum(item.bytes_scanned for item in results),
        "skipped_large_files": sum(item.skipped_large_files for item in results),
        "error_count": len(errors),
        "warning_count": len(warnings),
        "repositories": [
            {
                "repository": item.repository,
                "files_seen": item.files_seen,
                "text_files_scanned": item.text_files_scanned,
                "bytes_scanned": item.bytes_scanned,
                "skipped_large_files": item.skipped_large_files,
                "error_count": sum(1 for finding in (item.findings or []) if finding.severity == "error"),
                "warning_count": sum(1 for finding in (item.findings or []) if finding.severity == "warning"),
            }
            for item in results
        ],
        "findings": [asdict(item) for item in findings],
    }
    (OUTPUT_DIR / "public-sanitization.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    lines = [
        "# Public content and sanitation audit",
        "",
        f"Generated: `{generated_utc}`",
        "",
        f"- Repositories: **{len(results)}/{len(manifest['expected_public_repositories'])}**",
        f"- Files observed: **{payload['files_seen']}**",
        f"- Text files scanned: **{payload['text_files_scanned']}**",
        f"- Bytes scanned: **{payload['bytes_scanned']}**",
        f"- Errors: **{len(errors)}**",
        f"- Warnings: **{len(warnings)}**",
        "",
        "## Repository coverage",
        "",
        "| Repository | Files | Text scanned | Errors | Warnings |",
        "|---|---:|---:|---:|---:|",
    ]
    for item in results:
        item_errors = sum(1 for finding in (item.findings or []) if finding.severity == "error")
        item_warnings = sum(1 for finding in (item.findings or []) if finding.severity == "warning")
        lines.append(
            f"| {item.repository} | {item.files_seen} | {item.text_files_scanned} | "
            f"{item_errors} | {item_warnings} |"
        )
    lines.extend(["", "## Findings", ""])
    if not findings:
        lines.append("No findings.")
    else:
        for item in findings:
            location = item.path or "repository"
            if item.line is not None:
                location += f":{item.line}"
            lines.append(
                f"- **{item.severity.upper()}** `{item.repository}/{location}` "
                f"`{item.rule}` — {item.message}"
            )
            if item.excerpt:
                lines.append(f"  - `{item.excerpt}`")
    lines.extend(
        [
            "",
            RIGHTS_NOTICE,
            "",
            "This notice does not replace or infer a software license. Third-party components retain their respective notices and licenses.",
            "",
        ]
    )
    (OUTPUT_DIR / "public-sanitization.md").write_text("\n".join(lines), encoding="utf-8")
    return len(errors), len(warnings)


def main() -> int:
    manifest = load_manifest()
    owner = manifest["owner"]
    profile_repository = manifest["profile_repository"]
    repositories = list(manifest["expected_public_repositories"])
    results: list[RepositoryResult] = []
    with ThreadPoolExecutor(max_workers=4) as executor:
        futures = {
            executor.submit(scan_repository, owner, repository, profile_repository): repository
            for repository in repositories
        }
        for future in as_completed(futures):
            repository = futures[future]
            try:
                results.append(future.result())
            except Exception as exc:
                result = RepositoryResult(repository=repository)
                add_finding(
                    result,
                    severity="error",
                    rule="coverage.unexpected_failure",
                    path="",
                    line=None,
                    message=f"Unexpected scan failure: {type(exc).__name__}: {exc}",
                )
                results.append(result)
    results.sort(key=lambda item: item.repository.lower())
    errors, warnings = write_reports(manifest, results)
    print(
        f"Public sanitation audit: repositories={len(results)} "
        f"errors={errors} warnings={warnings}"
    )
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
